name: JavaDoc

on:
  push:
    branches:
      - pro

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Push JavaDoc to Dokumentation folder


        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions" && git add target/site/apidocs --force && git commit -m "Update JavaDoc" && git push --force
